### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by DearZack** [Quatja/Vorolay#1]
![1](https://cloud.githubusercontent.com/assets/17618134/21667851/56752616-d337-11e6-9c7e-28977bd8b786.png)
My code:
`
voronoiView = (VoronoiView) findViewById(R.id.voronoi);
        LayoutInflater layoutInflater = getLayoutInflater();
        for (int i = 0; i < 15; i++) {
            ImageView view = (ImageView) layoutInflater.inflate(R.layout.item_iv, null, false);
            view.setImageResource(R.drawable.p2_480);
            voronoiView.addView(view);
        }
`

**Comment by Quatja** [comment]
Set a scale type for your ImageView
