### ISSUE TITLE
images not cropped in API19

### ISSUE THREAD

**Issue by angelkoh** [Quatja/Vorolay#2]
![device-2017-01-10-151117](https://cloud.githubusercontent.com/assets/829758/21796966/37dd65c4-d747-11e6-9acc-892cea931a9d.png)
 
app works correctly on emulator with API24, but is not properly cropped on an API19 (android 4.2.2) device.
 
the code for adding the view is 

    for (int i = 0; i < count; i++) {
            RelativeLayout rl = (RelativeLayout) layoutInflater.inflate(R.layout.item_voronoi, null, false);
            ImageView view = ( ImageView) rl.findViewById(R.id.image);  
            view.setImageURI(uri); 
            vv.addView(rl);
        }

and the xml is 

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">
 
    <ImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop" />

</RelativeLayout>
```

**Comment by Quatja** [comment]
Android 4.2.2 uses API 17. But Canvas.clipPath() first supported only from API 18.
https://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported

To crop images properly you can add this line:
```java
voronoiView.setLayerType(LAYER_TYPE_SOFTWARE, null);
```
